services:
  app:
    depends_on:
      mysql:
        condition: service_healthy
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /usr/app
    container_name: app
    restart: always
    env_file: ./.env
    volumes:
      - './:/usr/app'
    ports:
      - '${APP_PORT:-3000}:3000'
    networks:
      - sail
    command: bun run start
    stdin_open: true
    tty: true

  mysql:
    image: 'mariadb:10'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'sail-mysql:/var/lib/mysql'
    networks:
      - sail
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s

  mailpit:
    image: 'axllent/mailpit:latest'
    container_name: mailpit
    restart: unless-stopped
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_UI_PORT:-8025}:8025'
    networks:
      - sail

networks:
  sail:
    driver: bridge
volumes:
  sail-mysql:
    driver: local
  sail-app:
    driver: local